### ISSUE TITLE
[Feature#0001] Need to add option to enable/disable relocation of nav buttons. 

### ISSUE THREAD

**Issue by Carpathias** [Carpathias/tgce-restyler-5e3#2]
Currently the relocation of the navigation buttons cannot be disabled. Some players may like sticking off to the side.

**Comment by Handyfon** [comment]
+1

**Comment by Carpathias** [comment]
Feature added in v1.1.0
Added configs to allow for nav tab relocation optionally. Can be set as default. Button location can be managed per sheet, or forced globally (per user) in the settings config.
