### ISSUE TITLE
Feature Request [Per Sheet Settings]

### ISSUE THREAD

**Issue by Handyfon** [Carpathias/tgce-restyler-5e3#3]
To enhance customization, it would be beneficial to implement changes on an individual sheet basis. This approach ensures that the sheets can be tailored to suit each character's unique attributes.

**Comment by Carpathias** [comment]
This is on the roadmap for v1.2.0 and is top priority. Thanks for the feedback.  :)

**Comment by Carpathias** [comment]
Just wanted to give an update, progress is going well on the per actor sheet settings feature. 

https://github.com/Carpathias/tgce-restyler-5e3/blob/main/pictures/2024-03-07_22-50-32.png?raw=true

**Comment by Carpathias** [comment]
about another week to polish it up. 
https://github.com/Carpathias/tgce-restyler-5e3/blob/main/pictures/2024-03-16_00-25-59.png?raw=true

**Comment by Carpathias** [comment]
V2.0.01 has been released and accommodates for individual actor edits.
