### ISSUE TITLE
Relocation Nav Button / Not working - Running on forge-vtt.com

### ISSUE THREAD

**Issue by Nostalgia2046** [Carpathias/tgce-restyler-5e3#4]
Preview of the issue : [https://gyazo.com/ec3d19f2cd2364b287822e7327604713](url)

**Chrome :** 

- Relocate nav button not working

**Edge :** 

- Image link for banner not recognized
- Relocate nav button not working

**Comment by Carpathias** [comment]
I have been able to isolate the line of code in the F12 debugger that the script is hanging on. The script is erroring when it tries to read the rules in the modules custom stylesheet, but the cssRules attribute is empty. It should not be, and the rules seems to be present when i look in the ELements and CSS. No resolution yet.

**Comment by Carpathias** [comment]
- Continuing to work on Issue#0002 
- After the v1.1.1 update Foundry/Forge did not recognize the update
- Manually installed v1.1.1 update from manifest in local dev instance and Forge-vtt instance
  - Nav tab functionality issues seemed resolved in Forge-vtt instance
  - Both Foundry and Forge prompting for update to 'new' version v1.1.0
- Removed all packages from Foundry Package Manager
  - Foundry now recoginzes v1.1.1 and installs successfully
  - Forge now recognizes v1.1.1, but issue with nav buttons persists
  - Manually installing from manifest fixes the issues
    - https://github.com/Carpathias/tgce-restyler-5e3/releases/download/v1.1.1/module.json
    - Need to uncheck the toggle for 'Install from the Bazaar if the package is found' when installing
- Recreated a new v1.1.1 package in Foundry Package Manager
- Will need to monitor and continue testing on Forge.

**Comment by Carpathias** [comment]
v1.2.0 has been released. In order for Forge-VTT to pickup the update I had to stop my server(s) completely. I tested this on Forge and all is working (for me). 

Please check the CHANGELOG. https://github.com/Carpathias/tgce-restyler-5e3/blob/main/CHANGELOG.md
