### ISSUE TITLE
Issue with DnD5e versions prior to 3.1

### ISSUE THREAD

**Issue by noctxpyre** [Carpathias/tgce-restyler-5e3#8]
![Bild_2024-04-11_061549989](https://github.com/Carpathias/tgce-restyler-5e3/assets/97793475/feb2bc6b-2053-46b7-b922-137e33800c42)

**Comment by Carpathias** [comment]
That's interesting. I will look into this later today. 

I take it the Restyler isn't opening at all?

**Comment by noctxpyre** [comment]
No, Restyler isn't opening.

**Comment by Carpathias** [comment]
Ahhh, you're balking on this line of code. 

const darkTheme = game.settings.get("dnd5e","theme") == "dark"

The mod is looking for wheteher or not the DnD5e dark theme is enabled. What version of DnD5e3 are you on? A 3.0.x version, prior to dark theme?

**Comment by Carpathias** [comment]
if you are on 3.1.x, is your theme mode set to automatic?

**Comment by noctxpyre** [comment]
I'm running 3.0.4

**Comment by Carpathias** [comment]
yeah, the setting the mod is looking for doesnt exist in that version, as dark mode was released in 3.1. Something i didnt think of, and will have to work out fix for. 

Consider upgrading to 3.1?

**Comment by Carpathias** [comment]
I can probably fix this pretty easy, but I'll have to build a new lab with 3.0.4 since I'm already data migrated to 3.1.x in my current dev lab. If you don't want to upgrade, I'll need a few days for this.

**Comment by noctxpyre** [comment]
Sadly not possible because of compability issues of another module for automations.

**Comment by Carpathias** [comment]
I'll try and get this resolved for you by the weekend. Updated the Issue title to reflect the problem better.

**Comment by Carpathias** [comment]
OK, I got this fixed, but I won't probably push the updated version out until later today/tonight. There's a couple other things I want to get in there as well, namely a couple of the localization strings aren't working, and I want to include a macro i created for copying a config from one actor to another.

**Comment by Carpathias** [comment]
Version 2.0.03 was released and resolves this issue.
