### ISSUE TITLE
Issue with "Biography" tab and "Hue-Rotation" feature

### ISSUE THREAD

**Issue by noctxpyre** [Carpathias/tgce-restyler-5e3#9]
When you use a darker color in the 3.0.4 version it is hard to red the text in the biography tab of the sheet and there is no option within Restyler to change the colors within that tabs text.
![Bild_2024-04-12_053448241](https://github.com/Carpathias/tgce-restyler-5e3/assets/97793475/3e54f42c-7031-4c8a-bc56-5e30b298b6f4)

Also, when you recolor the sheet via the hue-rotation feature it recolors the whole sheet. An option to restict the hue recolor to the header of the sheet only would be nice. In the feature it states it's for acessability, but a solely header recolor would be nice to fit it to the character portrait.

Normal Hue:
![image](https://github.com/Carpathias/tgce-restyler-5e3/assets/97793475/f64db36e-63b6-41aa-bd02-70d49b9ba502)

Recolored Hue to fit header color to character portrait color:
![image](https://github.com/Carpathias/tgce-restyler-5e3/assets/97793475/d33e1246-eb8b-448f-8642-e0eb8e19b074)

**Comment by Carpathias** [comment]
Both of these points make sense. 
1. I will add in a color selector for Biography text which will be included in the 'Other Sheet Elements' section of the Restyler UI. This will accommodate for creating darker color sheets in Light theme mode. 
2. I will add in an additional range slider in the Sheet Header section of the Restyler UI that will focus only on hue-rotation for the header. Earlier version of the mod only did hue-rotation on the header, so this will not be hard to put back in.

**Comment by Carpathias** [comment]
Header Hue rotation was added to the Restyler UI Sheet Header section. 

Added two new settings to accommodate the lack of dark mode text for system versions prior to 3.1. 
![issue9-1](https://github.com/Carpathias/tgce-restyler-5e3/assets/79472577/4cc53669-7251-476b-95e6-ba228350e350)


Note that the Trait labels on the Bio tab will be overwritten by the Trait labels setting that affects the main sheet tab.
![issue9-2](https://github.com/Carpathias/tgce-restyler-5e3/assets/79472577/7122b9b7-bc32-430b-a9d8-75a676437d74)

**Comment by Carpathias** [comment]
Closing issue.
